// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WkApi.Repositories.Data;

namespace WkApi.Migrations
{
    [DbContext(typeof(WkApiDbContext))]
    partial class WkApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WkApi.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ba8267c-a786-4e83-ae7f-28e5d2447253"),
                            Address = "11 Collins Street, Melbourne",
                            DateOfBirth = new DateTime(1991, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailId = "Test1@yahoo.com",
                            FirstName = "TestFirstName1",
                            Gender = 1,
                            LastName = "TestLastName1",
                            MobileNo = "0401645111",
                            PinCode = "1038"
                        },
                        new
                        {
                            Id = new Guid("d999c46b-e706-4fd9-a79b-fe27ef544f8a"),
                            Address = "22 Collins Street, Melbourne",
                            DateOfBirth = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailId = "Test2@yahoo.com",
                            FirstName = "TestFirstName2",
                            Gender = 2,
                            LastName = "TestLastName2",
                            MobileNo = "0401645222",
                            PinCode = "2038"
                        },
                        new
                        {
                            Id = new Guid("e8b77576-bdec-4c4b-adfa-b7d90e12f675"),
                            Address = "33 Collins Street, Melbourne",
                            DateOfBirth = new DateTime(1993, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailId = "Test3@yahoo.com",
                            FirstName = "TestFirstName3",
                            Gender = 0,
                            LastName = "TestLastName3",
                            MobileNo = "0401645333",
                            PinCode = "3038"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
